#!/bin/bash
#
shopt -s expand_aliases

# Run this script from within the CTBPprj singularity container, e.g.
# with "rws" specified as follows:
#
workdir=${PWD}/..
prjSIF=${workdir}/tools/CTBPprj.sif

alias rws="singularity exec -e -B${workdir} ${prjSIF}"


# Genome files preparation.
# For details, see the comments in the R scripts.
#

# Get the genome files:
#
time rws Rscript xpgMmus39-Step1.R >& log1

#real	0m43.521s
#user	0m37.405s
#sys	0m6.031s


# Build the bowtie2 index:
#
time rws Rscript xpgMmus39-Step2.R >& log2

#real	61m54.390s
#user	790m10.554s
#sys	3m48.515s


# Build the bwa index:
#
time rws Rscript xpgMmus39-Step3.R >& log3 

#real	66m4.321s
#user	65m33.294s
#sys	0m20.060s


# Get and save the genome annotation in UCSC style and create a gene name/ID table:
#
rws bash xpgMmus39-Step4.sh

# ... the script also creates Mmus_rRNA.fa (for pulling out reads matching rRNAs).


# Note: mm39.blacklist.bed and  mm39.excluderanges.bed were derived as per
#        ../tools/xinstall-ChIPQC.
