#!/bin/bash
#

DOWNLOADdir="TMPfromLOCAL"
NTHREADS=4

EXPERIMENT1="INPUT_e_2 H3K9me3_e_1 H3K9me3_e_2"
EXPERIMENT2="INPUT_e_3 CTBP2_e_1 HDAC1_e_1"

EXPERIMENT3="INPUT_e_4 CTBP2_e_2 HDAC1_e_2 LSD1_e_1 LSD1_e_2"

EXPERIMENT4="INPUT_n_3 CTBP2ko_n_1 CTBP2ko_n_2 CTBP2wt_n_1 CTBP2wt_n_2"


for i in ${EXPERIMENT1} ${EXPERIMENT2}
do
  mkdir ${i}
  cd ${i}
  \cp ../Makefile_PEreadPreparation_template Makefile_PEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" Makefile_PEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../../../downloads/${DOWNLOADdir}#;" Makefile_PEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f Makefile_PEreadPreparation_${i} >& err_${i}) &
  cd ..
done
wait

for i in ${EXPERIMENT3}
do
  mkdir ${i}
  cd ${i}
  \cp ../Makefile_PEreadPreparation_template Makefile_PEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" Makefile_PEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../../../downloads/${DOWNLOADdir}#;" Makefile_PEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f Makefile_PEreadPreparation_${i} >& err_${i}) &
  cd ..
done
wait

for i in ${EXPERIMENT4}
do
  mkdir ${i}
  cd ${i}
  \cp ../Makefile_PEreadPreparation_template Makefile_PEreadPreparation_${i}
  sed -i "s/SAMPLE         = LABEL/SAMPLE         = $i/;" Makefile_PEreadPreparation_${i}
  sed -i "s#FASTQDIR       = ../../../downloads/DOWNLOADdir#FASTQDIR       = ../../../downloads/${DOWNLOADdir}#;" Makefile_PEreadPreparation_${i}
  (make -j $NTHREADS -I../ -I../../ -f Makefile_PEreadPreparation_${i} >& err_${i}) &
  cd ..
done
wait

